name: Deploy to production
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: sandrabot/sandra/.github/workflows/build.yml@main

  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    needs: build
    steps:
      - name: Invoke deployment webhook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_type: 'form-urlencoded'
          webhook_url: ${{ secrets.DEPLOY_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.DEPLOY_WEBHOOK_SECRET }}
          data: 'runId=${{ github.run_id }}'
