name: Deploy to production
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-build:
    name: Reusable workflow
    uses: sandrabot/sandra/.github/workflows/test-build.yml@852be73f3d4e7af73a218757483ec2a624c846b3

  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    needs: test-build
    steps:
      - name: Invoke deployment webook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: 'runId=${{ github.run_id }}'
