name: Deploy to production
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-build:
    name: Reusable workflow
    uses: sandrabot/sandra/.github/workflows/test-build.yml@1e0ba1c57a16442d0770da72c519278bba095c3a

  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    needs: test-build
    steps:
      - name: Invoke deployment webook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: 'environment=production&token=${{ github.token }}'
