name: Pull Request Validation
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Verify the code still compiles
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: build
      - name: Get the short commit sha
        uses: actions/github-script@v5
        with:
          script: |
            const short_sha = context.sha.substring(0, 7)
            core.exportVariable('GITHUB_SHA_SHORT', short_sha)
      - name: Upload development artifacts
        uses: actions/upload-artifact@v2
        with:
          name: latest-$GITHUB_SHA_SHORT
          path: build/libs

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Verify there are no regressions
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: test
