name: Pull Request Validation
on: pull_request

jobs:
  test-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Verify that the code still compiles
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: build
      - name: Verify there are no regressions
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: test
      - name: Upload development artifacts
        uses: actions/upload-artifact@v2
        with:
          name: latest-build
          path: build/libs
