name: Test and build
on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Verify that all tests pass
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: test

  build:
    runs-on: ubuntu-latest
    needs: test
    env:
      GITHUB_SHA_SHORT: 00000000
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Compile the source code
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: build
      - name: Set the short commit sha
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -b 1-8)" >> $GITHUB_ENV
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: latest-${{env.GITHUB_SHA_SHORT}}
          path: build/libs
